name: CI/CD Pipeline for CommerceCore

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃 (최신 코드 가져오기)
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Java 17 환경 설정 (CommerceCore가 Spring Boot 기반이므로 JDK 필요)
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          
      # 3. Gradle wrapper 파일에 실행 권한 추가
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      # 4. Github Actions 러너의 공인 IP 가져오기
      - name: Get Github Actions IP
        id: ip
        run: |
          PUBLIC_IP=$(curl -s https://ifconfig.me)
          echo "::set-output name=public_ip::$PUBLIC_IP"
      
      # 5. NCP CLI 다운로드 및 자격 증명 설정
      - name: Setting NCP CLI & Credentials
        run: |
          cd ~
          wget https://www.ncloud.com/api/support/download/5/65
          unzip 65
          mkdir ~/.ncloud
          echo -e "[DEFAULT]\nncloud_access_key_id = ${{ secrets.NCP_ACCESS_KEY }}\nncloud_secret_access_key = ${{ secrets.NCP_SECRET_KEY }}" >> ~/.ncloud/configure

      # 6. 보안 그룹에 Github Actions IP 추가
      - name: Add Github Actions IP to DB Security Group
        run: |
          chmod -R 777 ~/cli_linux
          cd ~/cli_linux
          ./ncloud vserver addAccessControlGroupInboundRule --regionCode KR --vpcNo ${{ secrets.NCP_VPC_ID }} --accessControlGroupNo ${{ secrets.DB_ACG_ID }} --accessControlGroupRuleList "protocolTypeCode='TCP', ipBlock='${{ steps.ip.outputs.public_ip }}/32', portRange='3306'"

      # 7. Gradle 빌드 (Spring Boot 애플리케이션 빌드)
      - name: Build with Gradle
        run: ./gradlew build

      # 8. Docker 이미지 빌드 (Docker 이미지 생성)
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/commercecore .

      # 9. Docker Hub 로그인 (로그인 후 이미지 푸시)
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # 10. Docker 이미지 푸시 (Docker Hub에 이미지 업로드)
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/commercecore

  deploy:
    needs: build  # build 작업이 완료된 후 deploy 작업 실행
    runs-on: ubuntu-latest

    steps:
      # 7. SSH를 통해 NCP 서버로 접속 및 배포
      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.WAS_01_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/commercecore  # 새로운 이미지 가져오기
            docker stop commercecore || true  # 기존 컨테이너 중지
            docker rm commercecore || true    # 기존 컨테이너 제거
            docker run -d --name commercecore -p 8090:8090 ${{ secrets.DOCKER_HUB_USERNAME }}/commercecore  # 새로운 컨테이너 실행
